version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    restart: unless-stopped
    tty: true
    ports:
      - "8000:8000"
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql
    networks:
      - laravel_network

  mysql:
    image: mysql:8.0
    container_name: laravel-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel_network

#   phpmyadmin: # Opcional para facilitar o gerenciamento do MySQL
#     image: phpmyadmin/phpmyadmin
#     restart: unless-stopped
#     ports:
#       - "8080:80"
#     environment:
#       PMA_HOST: mysql
#       MYSQL_ROOT_PASSWORD: root
#     networks:
#       - laravel_network

volumes:
  dbdata:

networks:
  laravel_network:
    driver: bridge
